/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.itlifter.employee.service.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the CompanyTypeMaster service. Represents a row in the &quot;employee_CompanyTypeMaster&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.itlifter.employee.service.model.impl.CompanyTypeMasterModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.itlifter.employee.service.model.impl.CompanyTypeMasterImpl}.
 * </p>
 *
 * @author Ashish
 * @see CompanyTypeMaster
 * @see com.itlifter.employee.service.model.impl.CompanyTypeMasterImpl
 * @see com.itlifter.employee.service.model.impl.CompanyTypeMasterModelImpl
 * @generated
 */
public interface CompanyTypeMasterModel extends BaseModel<CompanyTypeMaster> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a company type master model instance should use the {@link CompanyTypeMaster} interface instead.
	 */

	/**
	 * Returns the primary key of this company type master.
	 *
	 * @return the primary key of this company type master
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this company type master.
	 *
	 * @param primaryKey the primary key of this company type master
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the type ID of this company type master.
	 *
	 * @return the type ID of this company type master
	 */
	public long getTypeId();

	/**
	 * Sets the type ID of this company type master.
	 *
	 * @param typeId the type ID of this company type master
	 */
	public void setTypeId(long typeId);

	/**
	 * Returns the type code of this company type master.
	 *
	 * @return the type code of this company type master
	 */
	@AutoEscape
	public String getTypeCode();

	/**
	 * Sets the type code of this company type master.
	 *
	 * @param TypeCode the type code of this company type master
	 */
	public void setTypeCode(String TypeCode);

	/**
	 * Returns the type name of this company type master.
	 *
	 * @return the type name of this company type master
	 */
	@AutoEscape
	public String getTypeName();

	/**
	 * Sets the type name of this company type master.
	 *
	 * @param TypeName the type name of this company type master
	 */
	public void setTypeName(String TypeName);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(CompanyTypeMaster companyTypeMaster);

	@Override
	public int hashCode();

	@Override
	public CacheModel<CompanyTypeMaster> toCacheModel();

	@Override
	public CompanyTypeMaster toEscapedModel();

	@Override
	public CompanyTypeMaster toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}