create table employee_CompanyRequest (
	requestId LONG not null primary key,
	companyId LONG,
	groupId LONG,
	userId LONG,
	cname VARCHAR(75) null,
	ctype VARCHAR(75) null,
	crecursable BOOLEAN,
	cregionId LONG,
	ccountryId LONG,
	caddress VARCHAR(75) null,
	cphone LONG,
	cwebsite VARCHAR(75) null,
	cemailAddress VARCHAR(75) null,
	caddress1 VARCHAR(75) null,
	caddress2 VARCHAR(75) null,
	carea VARCHAR(75) null,
	ccity VARCHAR(75) null,
	cdistrict VARCHAR(75) null,
	cstate VARCHAR(75) null,
	czipcode LONG,
	cfax LONG,
	title VARCHAR(75) null,
	firstName VARCHAR(75) null,
	lastName VARCHAR(75) null,
	designation VARCHAR(75) null,
	fax LONG,
	mobile LONG,
	email VARCHAR(75) null,
	status VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	userName VARCHAR(75) null,
	exts1 VARCHAR(75) null,
	exts2 VARCHAR(75) null,
	exts3 VARCHAR(75) null,
	exts4 VARCHAR(75) null,
	exts5 VARCHAR(75) null,
	exts6 VARCHAR(75) null,
	exts7 VARCHAR(75) null,
	exts8 VARCHAR(75) null,
	exts9 VARCHAR(75) null,
	extl10 LONG,
	extl11 LONG,
	extl12 LONG,
	extd13 DATE null,
	extd14 DATE null,
	extd15 DATE null
);

create table employee_CompanyTypeMaster (
	typeId LONG not null primary key,
	TypeCode VARCHAR(75) null,
	TypeName VARCHAR(75) null
);

create table employee_company_request (
	requestId LONG not null primary key,
	companyId LONG,
	groupId LONG,
	userId LONG,
	cname VARCHAR(75) null,
	ctype VARCHAR(75) null,
	crecursable BOOLEAN,
	cregionId LONG,
	ccountryId LONG,
	caddress VARCHAR(75) null,
	cphone LONG,
	cwebsite LONG,
	cemailAddress VARCHAR(75) null,
	caddress1 VARCHAR(75) null,
	caddress2 VARCHAR(75) null,
	carea VARCHAR(75) null,
	ccity VARCHAR(75) null,
	cdistrict VARCHAR(75) null,
	cstate VARCHAR(75) null,
	czipcode LONG,
	cfax LONG,
	title VARCHAR(75) null,
	firstName VARCHAR(75) null,
	lastName VARCHAR(75) null,
	designation VARCHAR(75) null,
	fax LONG,
	mobile LONG,
	email VARCHAR(75) null,
	status VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	userName VARCHAR(75) null,
	exts1 VARCHAR(75) null,
	exts2 VARCHAR(75) null,
	exts3 VARCHAR(75) null,
	exts4 VARCHAR(75) null,
	exts5 VARCHAR(75) null,
	exts6 VARCHAR(75) null,
	exts7 VARCHAR(75) null,
	exts8 VARCHAR(75) null,
	exts9 VARCHAR(75) null,
	extl10 LONG,
	extl11 LONG,
	extl12 LONG,
	extd13 DATE null,
	extd14 DATE null,
	extd15 DATE null
);