/**
 * Copyright (c) 2000-2013 Liferay, Inc. All rights reserved.
 *
 * The contents of this file are subject to the terms of the Liferay Enterprise
 * Subscription License ("License"). You may not use this file except in
 * compliance with the License. You can obtain a copy of the License by
 * contacting Liferay, Inc. See the License for the specific language governing
 * permissions and limitations under the License, including but not limited to
 * distribution rights of the Software.
 *
 *
 *
 */

package com.itlifter.employee.service.model.impl;

import com.itlifter.employee.service.model.CompanyRequest;
import com.itlifter.employee.service.model.CompanyRequestModel;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import java.io.Serializable;

import java.sql.Types;

import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the CompanyRequest service. Represents a row in the &quot;employee_CompanyRequest&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.itlifter.employee.service.model.CompanyRequestModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link CompanyRequestImpl}.
 * </p>
 *
 * @author Ashish
 * @see CompanyRequestImpl
 * @see com.itlifter.employee.service.model.CompanyRequest
 * @see com.itlifter.employee.service.model.CompanyRequestModel
 * @generated
 */
public class CompanyRequestModelImpl extends BaseModelImpl<CompanyRequest>
	implements CompanyRequestModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a company request model instance should use the {@link com.itlifter.employee.service.model.CompanyRequest} interface instead.
	 */
	public static final String TABLE_NAME = "employee_CompanyRequest";
	public static final Object[][] TABLE_COLUMNS = {
			{ "requestId", Types.BIGINT },
			{ "companyId", Types.BIGINT },
			{ "groupId", Types.BIGINT },
			{ "userId", Types.BIGINT },
			{ "cname", Types.VARCHAR },
			{ "ctype", Types.VARCHAR },
			{ "crecursable", Types.BOOLEAN },
			{ "cregionId", Types.BIGINT },
			{ "ccountryId", Types.BIGINT },
			{ "caddress", Types.VARCHAR },
			{ "cphone", Types.BIGINT },
			{ "cwebsite", Types.VARCHAR },
			{ "cemailAddress", Types.VARCHAR },
			{ "caddress1", Types.VARCHAR },
			{ "caddress2", Types.VARCHAR },
			{ "carea", Types.VARCHAR },
			{ "ccity", Types.VARCHAR },
			{ "cdistrict", Types.VARCHAR },
			{ "cstate", Types.VARCHAR },
			{ "czipcode", Types.BIGINT },
			{ "cfax", Types.BIGINT },
			{ "title", Types.VARCHAR },
			{ "firstName", Types.VARCHAR },
			{ "lastName", Types.VARCHAR },
			{ "designation", Types.VARCHAR },
			{ "fax", Types.BIGINT },
			{ "mobile", Types.BIGINT },
			{ "email", Types.VARCHAR },
			{ "status", Types.VARCHAR },
			{ "createDate", Types.TIMESTAMP },
			{ "modifiedDate", Types.TIMESTAMP },
			{ "userName", Types.VARCHAR },
			{ "exts1", Types.VARCHAR },
			{ "exts2", Types.VARCHAR },
			{ "exts3", Types.VARCHAR },
			{ "exts4", Types.VARCHAR },
			{ "exts5", Types.VARCHAR },
			{ "exts6", Types.VARCHAR },
			{ "exts7", Types.VARCHAR },
			{ "exts8", Types.VARCHAR },
			{ "exts9", Types.VARCHAR },
			{ "extl10", Types.BIGINT },
			{ "extl11", Types.BIGINT },
			{ "extl12", Types.BIGINT },
			{ "extd13", Types.TIMESTAMP },
			{ "extd14", Types.TIMESTAMP },
			{ "extd15", Types.TIMESTAMP }
		};
	public static final String TABLE_SQL_CREATE = "create table employee_CompanyRequest (requestId LONG not null primary key,companyId LONG,groupId LONG,userId LONG,cname VARCHAR(75) null,ctype VARCHAR(75) null,crecursable BOOLEAN,cregionId LONG,ccountryId LONG,caddress VARCHAR(75) null,cphone LONG,cwebsite VARCHAR(75) null,cemailAddress VARCHAR(75) null,caddress1 VARCHAR(75) null,caddress2 VARCHAR(75) null,carea VARCHAR(75) null,ccity VARCHAR(75) null,cdistrict VARCHAR(75) null,cstate VARCHAR(75) null,czipcode LONG,cfax LONG,title VARCHAR(75) null,firstName VARCHAR(75) null,lastName VARCHAR(75) null,designation VARCHAR(75) null,fax LONG,mobile LONG,email VARCHAR(75) null,status VARCHAR(75) null,createDate DATE null,modifiedDate DATE null,userName VARCHAR(75) null,exts1 VARCHAR(75) null,exts2 VARCHAR(75) null,exts3 VARCHAR(75) null,exts4 VARCHAR(75) null,exts5 VARCHAR(75) null,exts6 VARCHAR(75) null,exts7 VARCHAR(75) null,exts8 VARCHAR(75) null,exts9 VARCHAR(75) null,extl10 LONG,extl11 LONG,extl12 LONG,extd13 DATE null,extd14 DATE null,extd15 DATE null)";
	public static final String TABLE_SQL_DROP = "drop table employee_CompanyRequest";
	public static final String ORDER_BY_JPQL = " ORDER BY companyRequest.cname ASC";
	public static final String ORDER_BY_SQL = " ORDER BY employee_CompanyRequest.cname ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.itlifter.employee.service.model.CompanyRequest"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.itlifter.employee.service.model.CompanyRequest"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.column.bitmask.enabled.com.itlifter.employee.service.model.CompanyRequest"),
			true);
	public static long GROUPID_COLUMN_BITMASK = 1L;
	public static long CNAME_COLUMN_BITMASK = 2L;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.itlifter.employee.service.model.CompanyRequest"));

	public CompanyRequestModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _requestId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setRequestId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _requestId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return CompanyRequest.class;
	}

	@Override
	public String getModelClassName() {
		return CompanyRequest.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("requestId", getRequestId());
		attributes.put("companyId", getCompanyId());
		attributes.put("groupId", getGroupId());
		attributes.put("userId", getUserId());
		attributes.put("cname", getCname());
		attributes.put("ctype", getCtype());
		attributes.put("crecursable", getCrecursable());
		attributes.put("cregionId", getCregionId());
		attributes.put("ccountryId", getCcountryId());
		attributes.put("caddress", getCaddress());
		attributes.put("cphone", getCphone());
		attributes.put("cwebsite", getCwebsite());
		attributes.put("cemailAddress", getCemailAddress());
		attributes.put("caddress1", getCaddress1());
		attributes.put("caddress2", getCaddress2());
		attributes.put("carea", getCarea());
		attributes.put("ccity", getCcity());
		attributes.put("cdistrict", getCdistrict());
		attributes.put("cstate", getCstate());
		attributes.put("czipcode", getCzipcode());
		attributes.put("cfax", getCfax());
		attributes.put("title", getTitle());
		attributes.put("firstName", getFirstName());
		attributes.put("lastName", getLastName());
		attributes.put("designation", getDesignation());
		attributes.put("fax", getFax());
		attributes.put("mobile", getMobile());
		attributes.put("email", getEmail());
		attributes.put("status", getStatus());
		attributes.put("createDate", getCreateDate());
		attributes.put("modifiedDate", getModifiedDate());
		attributes.put("userName", getUserName());
		attributes.put("exts1", getExts1());
		attributes.put("exts2", getExts2());
		attributes.put("exts3", getExts3());
		attributes.put("exts4", getExts4());
		attributes.put("exts5", getExts5());
		attributes.put("exts6", getExts6());
		attributes.put("exts7", getExts7());
		attributes.put("exts8", getExts8());
		attributes.put("exts9", getExts9());
		attributes.put("extl10", getExtl10());
		attributes.put("extl11", getExtl11());
		attributes.put("extl12", getExtl12());
		attributes.put("extd13", getExtd13());
		attributes.put("extd14", getExtd14());
		attributes.put("extd15", getExtd15());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long requestId = (Long)attributes.get("requestId");

		if (requestId != null) {
			setRequestId(requestId);
		}

		Long companyId = (Long)attributes.get("companyId");

		if (companyId != null) {
			setCompanyId(companyId);
		}

		Long groupId = (Long)attributes.get("groupId");

		if (groupId != null) {
			setGroupId(groupId);
		}

		Long userId = (Long)attributes.get("userId");

		if (userId != null) {
			setUserId(userId);
		}

		String cname = (String)attributes.get("cname");

		if (cname != null) {
			setCname(cname);
		}

		String ctype = (String)attributes.get("ctype");

		if (ctype != null) {
			setCtype(ctype);
		}

		Boolean crecursable = (Boolean)attributes.get("crecursable");

		if (crecursable != null) {
			setCrecursable(crecursable);
		}

		Long cregionId = (Long)attributes.get("cregionId");

		if (cregionId != null) {
			setCregionId(cregionId);
		}

		Long ccountryId = (Long)attributes.get("ccountryId");

		if (ccountryId != null) {
			setCcountryId(ccountryId);
		}

		String caddress = (String)attributes.get("caddress");

		if (caddress != null) {
			setCaddress(caddress);
		}

		Long cphone = (Long)attributes.get("cphone");

		if (cphone != null) {
			setCphone(cphone);
		}

		String cwebsite = (String)attributes.get("cwebsite");

		if (cwebsite != null) {
			setCwebsite(cwebsite);
		}

		String cemailAddress = (String)attributes.get("cemailAddress");

		if (cemailAddress != null) {
			setCemailAddress(cemailAddress);
		}

		String caddress1 = (String)attributes.get("caddress1");

		if (caddress1 != null) {
			setCaddress1(caddress1);
		}

		String caddress2 = (String)attributes.get("caddress2");

		if (caddress2 != null) {
			setCaddress2(caddress2);
		}

		String carea = (String)attributes.get("carea");

		if (carea != null) {
			setCarea(carea);
		}

		String ccity = (String)attributes.get("ccity");

		if (ccity != null) {
			setCcity(ccity);
		}

		String cdistrict = (String)attributes.get("cdistrict");

		if (cdistrict != null) {
			setCdistrict(cdistrict);
		}

		String cstate = (String)attributes.get("cstate");

		if (cstate != null) {
			setCstate(cstate);
		}

		Long czipcode = (Long)attributes.get("czipcode");

		if (czipcode != null) {
			setCzipcode(czipcode);
		}

		Long cfax = (Long)attributes.get("cfax");

		if (cfax != null) {
			setCfax(cfax);
		}

		String title = (String)attributes.get("title");

		if (title != null) {
			setTitle(title);
		}

		String firstName = (String)attributes.get("firstName");

		if (firstName != null) {
			setFirstName(firstName);
		}

		String lastName = (String)attributes.get("lastName");

		if (lastName != null) {
			setLastName(lastName);
		}

		String designation = (String)attributes.get("designation");

		if (designation != null) {
			setDesignation(designation);
		}

		Long fax = (Long)attributes.get("fax");

		if (fax != null) {
			setFax(fax);
		}

		Long mobile = (Long)attributes.get("mobile");

		if (mobile != null) {
			setMobile(mobile);
		}

		String email = (String)attributes.get("email");

		if (email != null) {
			setEmail(email);
		}

		String status = (String)attributes.get("status");

		if (status != null) {
			setStatus(status);
		}

		Date createDate = (Date)attributes.get("createDate");

		if (createDate != null) {
			setCreateDate(createDate);
		}

		Date modifiedDate = (Date)attributes.get("modifiedDate");

		if (modifiedDate != null) {
			setModifiedDate(modifiedDate);
		}

		String userName = (String)attributes.get("userName");

		if (userName != null) {
			setUserName(userName);
		}

		String exts1 = (String)attributes.get("exts1");

		if (exts1 != null) {
			setExts1(exts1);
		}

		String exts2 = (String)attributes.get("exts2");

		if (exts2 != null) {
			setExts2(exts2);
		}

		String exts3 = (String)attributes.get("exts3");

		if (exts3 != null) {
			setExts3(exts3);
		}

		String exts4 = (String)attributes.get("exts4");

		if (exts4 != null) {
			setExts4(exts4);
		}

		String exts5 = (String)attributes.get("exts5");

		if (exts5 != null) {
			setExts5(exts5);
		}

		String exts6 = (String)attributes.get("exts6");

		if (exts6 != null) {
			setExts6(exts6);
		}

		String exts7 = (String)attributes.get("exts7");

		if (exts7 != null) {
			setExts7(exts7);
		}

		String exts8 = (String)attributes.get("exts8");

		if (exts8 != null) {
			setExts8(exts8);
		}

		String exts9 = (String)attributes.get("exts9");

		if (exts9 != null) {
			setExts9(exts9);
		}

		Long extl10 = (Long)attributes.get("extl10");

		if (extl10 != null) {
			setExtl10(extl10);
		}

		Long extl11 = (Long)attributes.get("extl11");

		if (extl11 != null) {
			setExtl11(extl11);
		}

		Long extl12 = (Long)attributes.get("extl12");

		if (extl12 != null) {
			setExtl12(extl12);
		}

		Date extd13 = (Date)attributes.get("extd13");

		if (extd13 != null) {
			setExtd13(extd13);
		}

		Date extd14 = (Date)attributes.get("extd14");

		if (extd14 != null) {
			setExtd14(extd14);
		}

		Date extd15 = (Date)attributes.get("extd15");

		if (extd15 != null) {
			setExtd15(extd15);
		}
	}

	@Override
	public long getRequestId() {
		return _requestId;
	}

	@Override
	public void setRequestId(long requestId) {
		_requestId = requestId;
	}

	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	@Override
	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	@Override
	public String getCname() {
		if (_cname == null) {
			return StringPool.BLANK;
		}
		else {
			return _cname;
		}
	}

	@Override
	public void setCname(String cname) {
		_columnBitmask = -1L;

		_cname = cname;
	}

	@Override
	public String getCtype() {
		if (_ctype == null) {
			return StringPool.BLANK;
		}
		else {
			return _ctype;
		}
	}

	@Override
	public void setCtype(String ctype) {
		_ctype = ctype;
	}

	@Override
	public boolean getCrecursable() {
		return _crecursable;
	}

	@Override
	public boolean isCrecursable() {
		return _crecursable;
	}

	@Override
	public void setCrecursable(boolean crecursable) {
		_crecursable = crecursable;
	}

	@Override
	public long getCregionId() {
		return _cregionId;
	}

	@Override
	public void setCregionId(long cregionId) {
		_cregionId = cregionId;
	}

	@Override
	public long getCcountryId() {
		return _ccountryId;
	}

	@Override
	public void setCcountryId(long ccountryId) {
		_ccountryId = ccountryId;
	}

	@Override
	public String getCaddress() {
		if (_caddress == null) {
			return StringPool.BLANK;
		}
		else {
			return _caddress;
		}
	}

	@Override
	public void setCaddress(String caddress) {
		_caddress = caddress;
	}

	@Override
	public long getCphone() {
		return _cphone;
	}

	@Override
	public void setCphone(long cphone) {
		_cphone = cphone;
	}

	@Override
	public String getCwebsite() {
		if (_cwebsite == null) {
			return StringPool.BLANK;
		}
		else {
			return _cwebsite;
		}
	}

	@Override
	public void setCwebsite(String cwebsite) {
		_cwebsite = cwebsite;
	}

	@Override
	public String getCemailAddress() {
		if (_cemailAddress == null) {
			return StringPool.BLANK;
		}
		else {
			return _cemailAddress;
		}
	}

	@Override
	public void setCemailAddress(String cemailAddress) {
		_cemailAddress = cemailAddress;
	}

	@Override
	public String getCaddress1() {
		if (_caddress1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _caddress1;
		}
	}

	@Override
	public void setCaddress1(String caddress1) {
		_caddress1 = caddress1;
	}

	@Override
	public String getCaddress2() {
		if (_caddress2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _caddress2;
		}
	}

	@Override
	public void setCaddress2(String caddress2) {
		_caddress2 = caddress2;
	}

	@Override
	public String getCarea() {
		if (_carea == null) {
			return StringPool.BLANK;
		}
		else {
			return _carea;
		}
	}

	@Override
	public void setCarea(String carea) {
		_carea = carea;
	}

	@Override
	public String getCcity() {
		if (_ccity == null) {
			return StringPool.BLANK;
		}
		else {
			return _ccity;
		}
	}

	@Override
	public void setCcity(String ccity) {
		_ccity = ccity;
	}

	@Override
	public String getCdistrict() {
		if (_cdistrict == null) {
			return StringPool.BLANK;
		}
		else {
			return _cdistrict;
		}
	}

	@Override
	public void setCdistrict(String cdistrict) {
		_cdistrict = cdistrict;
	}

	@Override
	public String getCstate() {
		if (_cstate == null) {
			return StringPool.BLANK;
		}
		else {
			return _cstate;
		}
	}

	@Override
	public void setCstate(String cstate) {
		_cstate = cstate;
	}

	@Override
	public long getCzipcode() {
		return _czipcode;
	}

	@Override
	public void setCzipcode(long czipcode) {
		_czipcode = czipcode;
	}

	@Override
	public long getCfax() {
		return _cfax;
	}

	@Override
	public void setCfax(long cfax) {
		_cfax = cfax;
	}

	@Override
	public String getTitle() {
		if (_title == null) {
			return StringPool.BLANK;
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@Override
	public String getFirstName() {
		if (_firstName == null) {
			return StringPool.BLANK;
		}
		else {
			return _firstName;
		}
	}

	@Override
	public void setFirstName(String firstName) {
		_firstName = firstName;
	}

	@Override
	public String getLastName() {
		if (_lastName == null) {
			return StringPool.BLANK;
		}
		else {
			return _lastName;
		}
	}

	@Override
	public void setLastName(String lastName) {
		_lastName = lastName;
	}

	@Override
	public String getDesignation() {
		if (_designation == null) {
			return StringPool.BLANK;
		}
		else {
			return _designation;
		}
	}

	@Override
	public void setDesignation(String designation) {
		_designation = designation;
	}

	@Override
	public long getFax() {
		return _fax;
	}

	@Override
	public void setFax(long fax) {
		_fax = fax;
	}

	@Override
	public long getMobile() {
		return _mobile;
	}

	@Override
	public void setMobile(long mobile) {
		_mobile = mobile;
	}

	@Override
	public String getEmail() {
		if (_email == null) {
			return StringPool.BLANK;
		}
		else {
			return _email;
		}
	}

	@Override
	public void setEmail(String email) {
		_email = email;
	}

	@Override
	public String getStatus() {
		if (_status == null) {
			return StringPool.BLANK;
		}
		else {
			return _status;
		}
	}

	@Override
	public void setStatus(String status) {
		_status = status;
	}

	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	@Override
	public String getUserName() {
		if (_userName == null) {
			return StringPool.BLANK;
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@Override
	public String getExts1() {
		if (_exts1 == null) {
			return StringPool.BLANK;
		}
		else {
			return _exts1;
		}
	}

	@Override
	public void setExts1(String exts1) {
		_exts1 = exts1;
	}

	@Override
	public String getExts2() {
		if (_exts2 == null) {
			return StringPool.BLANK;
		}
		else {
			return _exts2;
		}
	}

	@Override
	public void setExts2(String exts2) {
		_exts2 = exts2;
	}

	@Override
	public String getExts3() {
		if (_exts3 == null) {
			return StringPool.BLANK;
		}
		else {
			return _exts3;
		}
	}

	@Override
	public void setExts3(String exts3) {
		_exts3 = exts3;
	}

	@Override
	public String getExts4() {
		if (_exts4 == null) {
			return StringPool.BLANK;
		}
		else {
			return _exts4;
		}
	}

	@Override
	public void setExts4(String exts4) {
		_exts4 = exts4;
	}

	@Override
	public String getExts5() {
		if (_exts5 == null) {
			return StringPool.BLANK;
		}
		else {
			return _exts5;
		}
	}

	@Override
	public void setExts5(String exts5) {
		_exts5 = exts5;
	}

	@Override
	public String getExts6() {
		if (_exts6 == null) {
			return StringPool.BLANK;
		}
		else {
			return _exts6;
		}
	}

	@Override
	public void setExts6(String exts6) {
		_exts6 = exts6;
	}

	@Override
	public String getExts7() {
		if (_exts7 == null) {
			return StringPool.BLANK;
		}
		else {
			return _exts7;
		}
	}

	@Override
	public void setExts7(String exts7) {
		_exts7 = exts7;
	}

	@Override
	public String getExts8() {
		if (_exts8 == null) {
			return StringPool.BLANK;
		}
		else {
			return _exts8;
		}
	}

	@Override
	public void setExts8(String exts8) {
		_exts8 = exts8;
	}

	@Override
	public String getExts9() {
		if (_exts9 == null) {
			return StringPool.BLANK;
		}
		else {
			return _exts9;
		}
	}

	@Override
	public void setExts9(String exts9) {
		_exts9 = exts9;
	}

	@Override
	public long getExtl10() {
		return _extl10;
	}

	@Override
	public void setExtl10(long extl10) {
		_extl10 = extl10;
	}

	@Override
	public long getExtl11() {
		return _extl11;
	}

	@Override
	public void setExtl11(long extl11) {
		_extl11 = extl11;
	}

	@Override
	public long getExtl12() {
		return _extl12;
	}

	@Override
	public void setExtl12(long extl12) {
		_extl12 = extl12;
	}

	@Override
	public Date getExtd13() {
		return _extd13;
	}

	@Override
	public void setExtd13(Date extd13) {
		_extd13 = extd13;
	}

	@Override
	public Date getExtd14() {
		return _extd14;
	}

	@Override
	public void setExtd14(Date extd14) {
		_extd14 = extd14;
	}

	@Override
	public Date getExtd15() {
		return _extd15;
	}

	@Override
	public void setExtd15(Date extd15) {
		_extd15 = extd15;
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
			CompanyRequest.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public CompanyRequest toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (CompanyRequest)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		CompanyRequestImpl companyRequestImpl = new CompanyRequestImpl();

		companyRequestImpl.setRequestId(getRequestId());
		companyRequestImpl.setCompanyId(getCompanyId());
		companyRequestImpl.setGroupId(getGroupId());
		companyRequestImpl.setUserId(getUserId());
		companyRequestImpl.setCname(getCname());
		companyRequestImpl.setCtype(getCtype());
		companyRequestImpl.setCrecursable(getCrecursable());
		companyRequestImpl.setCregionId(getCregionId());
		companyRequestImpl.setCcountryId(getCcountryId());
		companyRequestImpl.setCaddress(getCaddress());
		companyRequestImpl.setCphone(getCphone());
		companyRequestImpl.setCwebsite(getCwebsite());
		companyRequestImpl.setCemailAddress(getCemailAddress());
		companyRequestImpl.setCaddress1(getCaddress1());
		companyRequestImpl.setCaddress2(getCaddress2());
		companyRequestImpl.setCarea(getCarea());
		companyRequestImpl.setCcity(getCcity());
		companyRequestImpl.setCdistrict(getCdistrict());
		companyRequestImpl.setCstate(getCstate());
		companyRequestImpl.setCzipcode(getCzipcode());
		companyRequestImpl.setCfax(getCfax());
		companyRequestImpl.setTitle(getTitle());
		companyRequestImpl.setFirstName(getFirstName());
		companyRequestImpl.setLastName(getLastName());
		companyRequestImpl.setDesignation(getDesignation());
		companyRequestImpl.setFax(getFax());
		companyRequestImpl.setMobile(getMobile());
		companyRequestImpl.setEmail(getEmail());
		companyRequestImpl.setStatus(getStatus());
		companyRequestImpl.setCreateDate(getCreateDate());
		companyRequestImpl.setModifiedDate(getModifiedDate());
		companyRequestImpl.setUserName(getUserName());
		companyRequestImpl.setExts1(getExts1());
		companyRequestImpl.setExts2(getExts2());
		companyRequestImpl.setExts3(getExts3());
		companyRequestImpl.setExts4(getExts4());
		companyRequestImpl.setExts5(getExts5());
		companyRequestImpl.setExts6(getExts6());
		companyRequestImpl.setExts7(getExts7());
		companyRequestImpl.setExts8(getExts8());
		companyRequestImpl.setExts9(getExts9());
		companyRequestImpl.setExtl10(getExtl10());
		companyRequestImpl.setExtl11(getExtl11());
		companyRequestImpl.setExtl12(getExtl12());
		companyRequestImpl.setExtd13(getExtd13());
		companyRequestImpl.setExtd14(getExtd14());
		companyRequestImpl.setExtd15(getExtd15());

		companyRequestImpl.resetOriginalValues();

		return companyRequestImpl;
	}

	@Override
	public int compareTo(CompanyRequest companyRequest) {
		int value = 0;

		value = getCname().compareTo(companyRequest.getCname());

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof CompanyRequest)) {
			return false;
		}

		CompanyRequest companyRequest = (CompanyRequest)obj;

		long primaryKey = companyRequest.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public void resetOriginalValues() {
		CompanyRequestModelImpl companyRequestModelImpl = this;

		companyRequestModelImpl._originalGroupId = companyRequestModelImpl._groupId;

		companyRequestModelImpl._setOriginalGroupId = false;

		companyRequestModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<CompanyRequest> toCacheModel() {
		CompanyRequestCacheModel companyRequestCacheModel = new CompanyRequestCacheModel();

		companyRequestCacheModel.requestId = getRequestId();

		companyRequestCacheModel.companyId = getCompanyId();

		companyRequestCacheModel.groupId = getGroupId();

		companyRequestCacheModel.userId = getUserId();

		companyRequestCacheModel.cname = getCname();

		String cname = companyRequestCacheModel.cname;

		if ((cname != null) && (cname.length() == 0)) {
			companyRequestCacheModel.cname = null;
		}

		companyRequestCacheModel.ctype = getCtype();

		String ctype = companyRequestCacheModel.ctype;

		if ((ctype != null) && (ctype.length() == 0)) {
			companyRequestCacheModel.ctype = null;
		}

		companyRequestCacheModel.crecursable = getCrecursable();

		companyRequestCacheModel.cregionId = getCregionId();

		companyRequestCacheModel.ccountryId = getCcountryId();

		companyRequestCacheModel.caddress = getCaddress();

		String caddress = companyRequestCacheModel.caddress;

		if ((caddress != null) && (caddress.length() == 0)) {
			companyRequestCacheModel.caddress = null;
		}

		companyRequestCacheModel.cphone = getCphone();

		companyRequestCacheModel.cwebsite = getCwebsite();

		String cwebsite = companyRequestCacheModel.cwebsite;

		if ((cwebsite != null) && (cwebsite.length() == 0)) {
			companyRequestCacheModel.cwebsite = null;
		}

		companyRequestCacheModel.cemailAddress = getCemailAddress();

		String cemailAddress = companyRequestCacheModel.cemailAddress;

		if ((cemailAddress != null) && (cemailAddress.length() == 0)) {
			companyRequestCacheModel.cemailAddress = null;
		}

		companyRequestCacheModel.caddress1 = getCaddress1();

		String caddress1 = companyRequestCacheModel.caddress1;

		if ((caddress1 != null) && (caddress1.length() == 0)) {
			companyRequestCacheModel.caddress1 = null;
		}

		companyRequestCacheModel.caddress2 = getCaddress2();

		String caddress2 = companyRequestCacheModel.caddress2;

		if ((caddress2 != null) && (caddress2.length() == 0)) {
			companyRequestCacheModel.caddress2 = null;
		}

		companyRequestCacheModel.carea = getCarea();

		String carea = companyRequestCacheModel.carea;

		if ((carea != null) && (carea.length() == 0)) {
			companyRequestCacheModel.carea = null;
		}

		companyRequestCacheModel.ccity = getCcity();

		String ccity = companyRequestCacheModel.ccity;

		if ((ccity != null) && (ccity.length() == 0)) {
			companyRequestCacheModel.ccity = null;
		}

		companyRequestCacheModel.cdistrict = getCdistrict();

		String cdistrict = companyRequestCacheModel.cdistrict;

		if ((cdistrict != null) && (cdistrict.length() == 0)) {
			companyRequestCacheModel.cdistrict = null;
		}

		companyRequestCacheModel.cstate = getCstate();

		String cstate = companyRequestCacheModel.cstate;

		if ((cstate != null) && (cstate.length() == 0)) {
			companyRequestCacheModel.cstate = null;
		}

		companyRequestCacheModel.czipcode = getCzipcode();

		companyRequestCacheModel.cfax = getCfax();

		companyRequestCacheModel.title = getTitle();

		String title = companyRequestCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			companyRequestCacheModel.title = null;
		}

		companyRequestCacheModel.firstName = getFirstName();

		String firstName = companyRequestCacheModel.firstName;

		if ((firstName != null) && (firstName.length() == 0)) {
			companyRequestCacheModel.firstName = null;
		}

		companyRequestCacheModel.lastName = getLastName();

		String lastName = companyRequestCacheModel.lastName;

		if ((lastName != null) && (lastName.length() == 0)) {
			companyRequestCacheModel.lastName = null;
		}

		companyRequestCacheModel.designation = getDesignation();

		String designation = companyRequestCacheModel.designation;

		if ((designation != null) && (designation.length() == 0)) {
			companyRequestCacheModel.designation = null;
		}

		companyRequestCacheModel.fax = getFax();

		companyRequestCacheModel.mobile = getMobile();

		companyRequestCacheModel.email = getEmail();

		String email = companyRequestCacheModel.email;

		if ((email != null) && (email.length() == 0)) {
			companyRequestCacheModel.email = null;
		}

		companyRequestCacheModel.status = getStatus();

		String status = companyRequestCacheModel.status;

		if ((status != null) && (status.length() == 0)) {
			companyRequestCacheModel.status = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			companyRequestCacheModel.createDate = createDate.getTime();
		}
		else {
			companyRequestCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			companyRequestCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			companyRequestCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		companyRequestCacheModel.userName = getUserName();

		String userName = companyRequestCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			companyRequestCacheModel.userName = null;
		}

		companyRequestCacheModel.exts1 = getExts1();

		String exts1 = companyRequestCacheModel.exts1;

		if ((exts1 != null) && (exts1.length() == 0)) {
			companyRequestCacheModel.exts1 = null;
		}

		companyRequestCacheModel.exts2 = getExts2();

		String exts2 = companyRequestCacheModel.exts2;

		if ((exts2 != null) && (exts2.length() == 0)) {
			companyRequestCacheModel.exts2 = null;
		}

		companyRequestCacheModel.exts3 = getExts3();

		String exts3 = companyRequestCacheModel.exts3;

		if ((exts3 != null) && (exts3.length() == 0)) {
			companyRequestCacheModel.exts3 = null;
		}

		companyRequestCacheModel.exts4 = getExts4();

		String exts4 = companyRequestCacheModel.exts4;

		if ((exts4 != null) && (exts4.length() == 0)) {
			companyRequestCacheModel.exts4 = null;
		}

		companyRequestCacheModel.exts5 = getExts5();

		String exts5 = companyRequestCacheModel.exts5;

		if ((exts5 != null) && (exts5.length() == 0)) {
			companyRequestCacheModel.exts5 = null;
		}

		companyRequestCacheModel.exts6 = getExts6();

		String exts6 = companyRequestCacheModel.exts6;

		if ((exts6 != null) && (exts6.length() == 0)) {
			companyRequestCacheModel.exts6 = null;
		}

		companyRequestCacheModel.exts7 = getExts7();

		String exts7 = companyRequestCacheModel.exts7;

		if ((exts7 != null) && (exts7.length() == 0)) {
			companyRequestCacheModel.exts7 = null;
		}

		companyRequestCacheModel.exts8 = getExts8();

		String exts8 = companyRequestCacheModel.exts8;

		if ((exts8 != null) && (exts8.length() == 0)) {
			companyRequestCacheModel.exts8 = null;
		}

		companyRequestCacheModel.exts9 = getExts9();

		String exts9 = companyRequestCacheModel.exts9;

		if ((exts9 != null) && (exts9.length() == 0)) {
			companyRequestCacheModel.exts9 = null;
		}

		companyRequestCacheModel.extl10 = getExtl10();

		companyRequestCacheModel.extl11 = getExtl11();

		companyRequestCacheModel.extl12 = getExtl12();

		Date extd13 = getExtd13();

		if (extd13 != null) {
			companyRequestCacheModel.extd13 = extd13.getTime();
		}
		else {
			companyRequestCacheModel.extd13 = Long.MIN_VALUE;
		}

		Date extd14 = getExtd14();

		if (extd14 != null) {
			companyRequestCacheModel.extd14 = extd14.getTime();
		}
		else {
			companyRequestCacheModel.extd14 = Long.MIN_VALUE;
		}

		Date extd15 = getExtd15();

		if (extd15 != null) {
			companyRequestCacheModel.extd15 = extd15.getTime();
		}
		else {
			companyRequestCacheModel.extd15 = Long.MIN_VALUE;
		}

		return companyRequestCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(95);

		sb.append("{requestId=");
		sb.append(getRequestId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", cname=");
		sb.append(getCname());
		sb.append(", ctype=");
		sb.append(getCtype());
		sb.append(", crecursable=");
		sb.append(getCrecursable());
		sb.append(", cregionId=");
		sb.append(getCregionId());
		sb.append(", ccountryId=");
		sb.append(getCcountryId());
		sb.append(", caddress=");
		sb.append(getCaddress());
		sb.append(", cphone=");
		sb.append(getCphone());
		sb.append(", cwebsite=");
		sb.append(getCwebsite());
		sb.append(", cemailAddress=");
		sb.append(getCemailAddress());
		sb.append(", caddress1=");
		sb.append(getCaddress1());
		sb.append(", caddress2=");
		sb.append(getCaddress2());
		sb.append(", carea=");
		sb.append(getCarea());
		sb.append(", ccity=");
		sb.append(getCcity());
		sb.append(", cdistrict=");
		sb.append(getCdistrict());
		sb.append(", cstate=");
		sb.append(getCstate());
		sb.append(", czipcode=");
		sb.append(getCzipcode());
		sb.append(", cfax=");
		sb.append(getCfax());
		sb.append(", title=");
		sb.append(getTitle());
		sb.append(", firstName=");
		sb.append(getFirstName());
		sb.append(", lastName=");
		sb.append(getLastName());
		sb.append(", designation=");
		sb.append(getDesignation());
		sb.append(", fax=");
		sb.append(getFax());
		sb.append(", mobile=");
		sb.append(getMobile());
		sb.append(", email=");
		sb.append(getEmail());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append(", createDate=");
		sb.append(getCreateDate());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", userName=");
		sb.append(getUserName());
		sb.append(", exts1=");
		sb.append(getExts1());
		sb.append(", exts2=");
		sb.append(getExts2());
		sb.append(", exts3=");
		sb.append(getExts3());
		sb.append(", exts4=");
		sb.append(getExts4());
		sb.append(", exts5=");
		sb.append(getExts5());
		sb.append(", exts6=");
		sb.append(getExts6());
		sb.append(", exts7=");
		sb.append(getExts7());
		sb.append(", exts8=");
		sb.append(getExts8());
		sb.append(", exts9=");
		sb.append(getExts9());
		sb.append(", extl10=");
		sb.append(getExtl10());
		sb.append(", extl11=");
		sb.append(getExtl11());
		sb.append(", extl12=");
		sb.append(getExtl12());
		sb.append(", extd13=");
		sb.append(getExtd13());
		sb.append(", extd14=");
		sb.append(getExtd14());
		sb.append(", extd15=");
		sb.append(getExtd15());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(145);

		sb.append("<model><model-name>");
		sb.append("com.itlifter.employee.service.model.CompanyRequest");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>requestId</column-name><column-value><![CDATA[");
		sb.append(getRequestId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cname</column-name><column-value><![CDATA[");
		sb.append(getCname());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ctype</column-name><column-value><![CDATA[");
		sb.append(getCtype());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>crecursable</column-name><column-value><![CDATA[");
		sb.append(getCrecursable());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cregionId</column-name><column-value><![CDATA[");
		sb.append(getCregionId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ccountryId</column-name><column-value><![CDATA[");
		sb.append(getCcountryId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>caddress</column-name><column-value><![CDATA[");
		sb.append(getCaddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cphone</column-name><column-value><![CDATA[");
		sb.append(getCphone());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cwebsite</column-name><column-value><![CDATA[");
		sb.append(getCwebsite());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cemailAddress</column-name><column-value><![CDATA[");
		sb.append(getCemailAddress());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>caddress1</column-name><column-value><![CDATA[");
		sb.append(getCaddress1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>caddress2</column-name><column-value><![CDATA[");
		sb.append(getCaddress2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>carea</column-name><column-value><![CDATA[");
		sb.append(getCarea());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>ccity</column-name><column-value><![CDATA[");
		sb.append(getCcity());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cdistrict</column-name><column-value><![CDATA[");
		sb.append(getCdistrict());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cstate</column-name><column-value><![CDATA[");
		sb.append(getCstate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>czipcode</column-name><column-value><![CDATA[");
		sb.append(getCzipcode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>cfax</column-name><column-value><![CDATA[");
		sb.append(getCfax());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>title</column-name><column-value><![CDATA[");
		sb.append(getTitle());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>firstName</column-name><column-value><![CDATA[");
		sb.append(getFirstName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>lastName</column-name><column-value><![CDATA[");
		sb.append(getLastName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>designation</column-name><column-value><![CDATA[");
		sb.append(getDesignation());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>fax</column-name><column-value><![CDATA[");
		sb.append(getFax());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>mobile</column-name><column-value><![CDATA[");
		sb.append(getMobile());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>email</column-name><column-value><![CDATA[");
		sb.append(getEmail());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>createDate</column-name><column-value><![CDATA[");
		sb.append(getCreateDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userName</column-name><column-value><![CDATA[");
		sb.append(getUserName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>exts1</column-name><column-value><![CDATA[");
		sb.append(getExts1());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>exts2</column-name><column-value><![CDATA[");
		sb.append(getExts2());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>exts3</column-name><column-value><![CDATA[");
		sb.append(getExts3());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>exts4</column-name><column-value><![CDATA[");
		sb.append(getExts4());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>exts5</column-name><column-value><![CDATA[");
		sb.append(getExts5());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>exts6</column-name><column-value><![CDATA[");
		sb.append(getExts6());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>exts7</column-name><column-value><![CDATA[");
		sb.append(getExts7());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>exts8</column-name><column-value><![CDATA[");
		sb.append(getExts8());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>exts9</column-name><column-value><![CDATA[");
		sb.append(getExts9());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>extl10</column-name><column-value><![CDATA[");
		sb.append(getExtl10());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>extl11</column-name><column-value><![CDATA[");
		sb.append(getExtl11());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>extl12</column-name><column-value><![CDATA[");
		sb.append(getExtl12());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>extd13</column-name><column-value><![CDATA[");
		sb.append(getExtd13());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>extd14</column-name><column-value><![CDATA[");
		sb.append(getExtd14());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>extd15</column-name><column-value><![CDATA[");
		sb.append(getExtd15());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static ClassLoader _classLoader = CompanyRequest.class.getClassLoader();
	private static Class<?>[] _escapedModelInterfaces = new Class[] {
			CompanyRequest.class
		};
	private long _requestId;
	private long _companyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private String _userUuid;
	private String _cname;
	private String _ctype;
	private boolean _crecursable;
	private long _cregionId;
	private long _ccountryId;
	private String _caddress;
	private long _cphone;
	private String _cwebsite;
	private String _cemailAddress;
	private String _caddress1;
	private String _caddress2;
	private String _carea;
	private String _ccity;
	private String _cdistrict;
	private String _cstate;
	private long _czipcode;
	private long _cfax;
	private String _title;
	private String _firstName;
	private String _lastName;
	private String _designation;
	private long _fax;
	private long _mobile;
	private String _email;
	private String _status;
	private Date _createDate;
	private Date _modifiedDate;
	private String _userName;
	private String _exts1;
	private String _exts2;
	private String _exts3;
	private String _exts4;
	private String _exts5;
	private String _exts6;
	private String _exts7;
	private String _exts8;
	private String _exts9;
	private long _extl10;
	private long _extl11;
	private long _extl12;
	private Date _extd13;
	private Date _extd14;
	private Date _extd15;
	private long _columnBitmask;
	private CompanyRequest _escapedModel;
}